name: CI - Build Docker Images

on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"

env:
  IMAGE_TAG: ${{ github.run_number }}
  FRONTEND_REPO: devops-assignment-frontend
  BACKEND_REPO: devops-assignment-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      # Frontend
      - name: Build & push frontend
        run: |
          docker build -t $FRONTEND_REPO:$IMAGE_TAG frontend
          docker tag $FRONTEND_REPO:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$FRONTEND_REPO:$IMAGE_TAG

      # Backend
      - name: Build & push backend
        run: |
          docker build -t $BACKEND_REPO:$IMAGE_TAG backend
          docker tag $BACKEND_REPO:$IMAGE_TAG \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$BACKEND_REPO:$IMAGE_TAG